-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 22:53:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema galix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema galix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `galix` DEFAULT CHARACTER SET utf8 ;
USE `galix` ;

-- -----------------------------------------------------
-- Table `galix`.`soldier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galix`.`soldier` ;

CREATE TABLE IF NOT EXISTS `galix`.`soldier` (
  `id` INT NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `currency` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galix`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galix`.`product` ;

CREATE TABLE IF NOT EXISTS `galix`.`product` (
  `id` INT NOT NULL,
  `product` VARCHAR(80) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `galix`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `galix`.`items` ;

CREATE TABLE IF NOT EXISTS `galix`.`items` (
  `soldier_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `soldier_id_idx` (`soldier_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `soldier_id`
    FOREIGN KEY (`soldier_id`)
    REFERENCES `galix`.`soldier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `galix`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
